### ISSUE TITLE
DescriptionAttribute inheritance

### ISSUE THREAD

**Issue by DaleyKD** [unchase/Unchase.Swashbuckle.AspNetCore.Extensions#12]
If I inherit from `DescriptionAttribute`, it appears that you don't attempt to search the inheritance chain.

Any chance you'd consider changing https://github.com/unchase/Unchase.Swashbuckle.AspNetCore.Extensions/blob/c48232cfa09ade23aa2b1addbddd2d0e5bebe502/src/Unchase.Swashbuckle.AspNetCore.Extensions/Extensions/EnumTypeExtensions.cs#L47 to use `true` instead of `false` ?

Thanks for the consideration!

**Comment by unchase** [comment]
Hi, @DaleyKD 
Done!)

**Comment by DaleyKD** [comment]
Dude, you rock.  That worked!

**Comment by unchase** [comment]
You are welcome!
