### ISSUE TITLE
Feature Request: Support x-enum-varnames

### ISSUE THREAD

**Issue by meinsiedler** [unchase/Unchase.Swashbuckle.AspNetCore.Extensions#18]
Hi!

The OpenAPI Generator uses `x-enum-varnames` to define names of the enum items as stated in the docs: https://openapi-generator.tech/docs/templating/#all-generators-core

> `x-enum-varnames` can be used to have an other enum name for the corresponding value. This is used to define names of the enum items.

Would it be possible to support `x-enum-varnames` additionally to `x-enumNames` so that the OpenAPI generator can generate the correct enum variable names?

**Comment by unchase** [comment]
Hi, @meinsiedler 

Yes, I will add this feature a little later

**Comment by unchase** [comment]
@meinsiedler done. See the latest version.

**Comment by meinsiedler** [comment]
Nice, thank you @unchase!

**Comment by cryo75** [comment]
How do I need to configure the swagger gen to have this feature?

**Comment by craustin** [comment]
```csharp
services
    .AddSwaggerGen(options =>
    {
        options.AddEnumsWithValuesFixFilters();  // will set x-enumNames and x-enumDescriptions
    });
```

or do this to use the hyphen-separated names:
```csharp
services
    .AddSwaggerGen(options =>
    {
        options.AddEnumsWithValuesFixFilters(fixEnumsOptions =>
        {
            fixEnumsOptions.XEnumNamesAlias = "x-enum-varnames";
            fixEnumsOptions.XEnumDescriptionsAlias = "x-enum-descriptions";
        });
    });
```
