### ISSUE TITLE
FEATURE Support for Swashbuckle.AspNetCore 5.0.0-beta or later

### ISSUE THREAD

**Issue by Advitalitum** [unchase/Unchase.Swashbuckle.AspNetCore.Extensions#2]
Will there be support for Swashbuckle.AspNetCore 5.0.0-beta or later?

**Comment by unchase** [comment]
Yes, I’ll add this feature soon (along with the release version of Swashbuckle.AspNetCore 5.0.0).

**Comment by ZeVS777** [comment]
as for now, I have a workaround like this:
https://gist.github.com/ZeVS777/55e0139f9533976c1ae15d24fb0f32f5

It does not support Description attribute, and in this solution DisplayEnumsWithValuesDocumentFilter depends on XEnumNamesSchemaFilter. So you can only add options.AddEnumsWithValuesFixFilters()

tested for enum parameters (body, query, head, path) using Swashbuckle.AspNetCore 5.0.0-rc

**Comment by andreslozadamosto** [comment]
There is no fix deployed yet, right?

**Comment by unchase** [comment]
Waiting [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) release version.

**Comment by amphasis** [comment]
> Waiting [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) release version.

Swashbuckle.AspNetCore released 24 days ago. When does Extensions release planned?

**Comment by unchase** [comment]
@amphasis 
In a process. I plan to complete it on this weekend.
