### ISSUE TITLE
Compatible with ASP.NET Core 6?

### ISSUE THREAD

**Issue by lonix1** [unchase/Unchase.Swashbuckle.AspNetCore.Extensions#23]
Hi @unchase

Do you know if this library works with v6?

I upgraded my project from v5 to v6. It was working in v5. But this does not work anymore:
````cs
options.AddEnumsWithValuesFixFilters(services, o => {
  o.IncludeDescriptions = true;
  o.DescriptionSource = DescriptionSources.XmlComments;
  o.IncludeXmlCommentsFrom(path);
});
````

The  error is:
> System.InvalidOperationException in Microsoft.AspNetCore.dll: 'Cannot modify ServiceCollection after application is built.'

Do you use this library successfully with v6?

**Comment by lonix1** [comment]
I think the problem [is here](https://github.com/unchase/Unchase.Swashbuckle.AspNetCore.Extensions/blob/d710cb6557944c49824d0cb31b72b90ad0319c1f/src/Unchase.Swashbuckle.AspNetCore.Extensions/Extensions/SwaggerGenOptionsExtensions.cs#L82). But I don't know why it worked in v5 but not v6.

**Comment by andreireinus** [comment]
I used this way, and it worked for me.

```csharp
builder.Services.AddSwaggerGen(options =>
{
    options.AddEnumsWithValuesFixFilters(null, enumsOptions =>
    {
        enumsOptions.XEnumNamesAlias = "x-enum-varnames";
    });
});
```

**Comment by gebiWangshushu** [comment]
https://www.cnblogs.com/xiaxiaolu/p/16247490.html worked
