### ISSUE TITLE
Imposible to use AddEnumValuesDescriptions with enums to string mapping

### ISSUE THREAD

**Issue by ketovdk** [unchase/Unchase.Swashbuckle.AspNetCore.Extensions#6]
AddEnumValuesDescription with System.InvalidCastException: Unable to cast object of type 'Microsoft.OpenApi.Any.OpenApiString' to type 'Microsoft.OpenApi.Any.OpenApiInteger'.

To reproduce:
Use json enumToStringMapping with 
`.AddJsonOptions(
					options => options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()))`
Use `options.AddEnumsWithValuesFixFilters(true);` in AddSwaggerGen

**Comment by unchase** [comment]
Hi, @ketovdk 
Using `AddEnumsWithValuesFixFilters` becomes useless if you use `JsonStringEnumConverter`.
But I agree that the error must be fixed.

It can display the following (after fix):
![enum](https://user-images.githubusercontent.com/29679226/77244853-f0a51b80-6c2a-11ea-8657-9caac2677dc1.png)

for:

```csharp
    /// <summary>
    /// Tag for TodoItem.
    /// </summary>
    [Description("Tag enum")]
    public enum Tag
    {
        /// <summary>
        /// None.
        /// </summary>
        [Description("Default tag")]
        None = 0,

        /// <summary>
        /// Task.
        /// </summary>
        [Description("Some task")]
        Task = 1,

        /// <summary>
        /// Workout.
        /// </summary>
        [Description("Periodical job")]
        Workout = 2
    }
```
